### ISSUE TITLE
Script Invocation Error

### ISSUE THREAD

**Issue by tomvanhelderen** [4np/TVGemist#11]
I've got an issue in Pods project:
Shell Script Invocation Error
> Command /bin/sh failed with exit code 1... 

![schermafbeelding 2018-08-16 om 20 19 32](https://user-images.githubusercontent.com/22304029/44227259-74b33980-a192-11e8-93a2-aa64fc940a8a.png)

**Comment by 4np** [comment]
Try cleaning your build folder by pressing `Command+Option+Shift+K` (same as [here](https://github.com/4np/TVGemist/issues/8#issuecomment-377775358) ;)). Does that help?

**Comment by tomvanhelderen** [comment]
Nope, the same error occurs... :(

**Comment by 4np** [comment]
I downloaded the [0.0.5 archive](
https://github.com/4np/TVGemist/archive/0.0.5.tar.gz) and compiled it without issues. I am sure it is caused by the cache / derived data. 

Close `Xcode`, open `Terminal` and remove all derived data:

```
rm -rf ~/Library/Developer/Xcode/DerivedData
```

Does that help?

What Xcode version are you using? I'm on `9.4.1`, the latest:

<img width="642" alt="screen shot 2018-08-17 at 19 00 32" src="https://user-images.githubusercontent.com/1049693/44278910-c968ba00-a24f-11e8-991b-9c1fe74896e7.png">

**Comment by tomvanhelderen** [comment]
It works! I use 9.4.1 indeed, and with the terminalcommand it is fixed! Thanks!
