### ISSUE TITLE
probleem met de swift compiler

### ISSUE THREAD

**Issue by tomvanhelderen** [4np/TVGemist#8]
## Extra information

Version you are using: ?

tvOS version: ?

Xcode version: ?

**Comment by tomvanhelderen** [comment]
![schermafbeelding 2018-03-31 om 23 01 25](https://user-images.githubusercontent.com/22304029/38167589-c268e1f6-3537-11e8-81c4-06b5ead254ec.png)

**Comment by 4np** [comment]
It sounds like you're still using `Xcode 9.2` as `compactMap` is new in `Swift 4.1` (which is bundled with `Xcode 9.3`). You need to go into Software Update and update Xcode to `9.3` in order to build (as stated [here](https://github.com/4np/TVGemist/releases/tag/0.0.4)). 

<img width="1181" alt="screen shot 2018-03-30 at 09 20 32" src="https://user-images.githubusercontent.com/1049693/38128696-f5b858a8-33fb-11e8-80af-3384d1789878.png">

If you keep running into build issues, try cleaning: 

1) COMMAND-SHIFT-K before building
2) or, in Terminal: `rm -rf ~/Library/Developer/Xcode/DerivedData/` before building

**Comment by technimad** [comment]
I had the same issue. An update of Xcode did fix this.

**Comment by tomvanhelderen** [comment]
Yup, it's fixed! :)
