### ISSUE TITLE
Favorites [Feature request]

### ISSUE THREAD

**Issue by rm335** [4np/TVGemist#9]
Hi there! First of all, we love TV Gemist!

In the deprecated version [Uitzending Gemist](https://github.com/4np/UitzendingGemist) users had the opportunity to mark shows as favorite. With this function you could quickly lookup new or missed episodes. Are you planning to add this feature to TV Gemist?

**Comment by 4np** [comment]
Yes, that's definitely part of the plans :)

**Comment by rm335** [comment]
Great! I assume you run this project in your spare time but could you reveal some plans for the near feature?

**Comment by RobDaPraia** [comment]
Yes would be great! Thanking in advance :)

**Comment by 4np** [comment]
@rm335 not really as this project is relatively agile and ad-hoc :) But other than favouriting I plan to add an episode UI to display the details of an episode (which Uitzending Gemist had) instead of playing it directly. I still want to get Apple FairPlay streams working, but I don't know if that's even possible.

**Comment by rm335** [comment]
Cool, since [KNIPPR](https://www.knippr.nl/) announced to stop it's services I was looking for a complete (public, commercial & expandable) alternative. TV Gemist is the best alternative in my opinion. 

If you need any help, please drop me a line.

**Comment by 4np** [comment]
Closing as this issue is not relevant anymore.
